version: "3"
services:
  react-app:
    build: .
    container_name: react-container
    ports:
      - "80:80"
      - "443:443"
    networks:
      kihelp-network:
        aliases:
          - react-app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  kihelp-network:
    external: true